CourseReg/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseReg.Models;
using CourseReg.ViewModel;

namespace CourseReg.Controllers
{
    public class SubjectsController : Controller
    {
         private ApplicationDbContext _context;

        public SubjectsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Subjects
        public ActionResult Index()
        {
            var list = _context.Database.SqlQuery<Subject_VMQ>("SELECT   Books.id, Books.Name, Chemesters.Name AS ChemsterName FROM Books INNER JOIN Chemesters ON Books.Chemsterid = Chemesters.id").ToList();
            return View(list);
        }
        public ActionResult Create(Books Books)
        {
            var list = _context.tbl_Chemester.ToList();
            var viewmodel = new Subject_VM
            {
                Books=Books,
                ScmesterList=list
            };
            return View(viewmodel);
        }   
        public ActionResult Save(Books Books)
        {
            string vardirection;
            if (Books.id == 0)
            {
                _context.tbl_Books.Add(Books);
                vardirection = "create";
            }
            else
            {
                var Booksdb = _context.tbl_Books.SingleOrDefault(c => c.id == Books.id);
                Booksdb.Name = Books.Name;
                Booksdb.Chemsterid = Books.Chemsterid;
               
                vardirection = "Index";
            }
            _context.SaveChanges();
            return RedirectToAction(vardirection);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            var listed = _context.tbl_Books.SingleOrDefault(c => c.id == id);
            var list = _context.tbl_Chemester.ToList();
            var viewmodel = new Subject_VM
            {
                Books = listed,
                ScmesterList = list
            };
          
            return View("create", viewmodel);
        }
        public ActionResult Delete(int id)
        {
            var Employee = _context.tbl_Books.SingleOrDefault(c => c.id == id);
            _context.tbl_Books.Remove(Employee);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CourseReg/Views/Subjects/Create.cshtml
@model CourseReg.ViewModel.Subject_VM
@{
    ViewBag.Title = "Create";
}
<h2>Register Book</h2>
<div class="col-md-offset-5 pull-right" style="margin-top:-40px">
    <a href="@Url.Action("Index","Subjects")" class="btn btn-primary">List Content</a>
</div>
@using (Html.BeginForm("Save", "Subjects", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
      
        <div class="col-md-3">
            <label>Select Semester</label>
            @Html.DropDownListFor(m => m.Books.Chemsterid, new SelectList(Model.ScmesterList, "id", "Name"), "Select Semester", htmlAttributes: new { @class = "form-control input-xs", })
        </div>
        <div class="col-md-3 ">
            <label>Name</label>
            @Html.TextBoxFor(m => m.Books.Name, new { @class = "form-control", @placeholder = "Name...", maxlength = "20", })
        </div>
        <div class="form-group" style="margin-top:20px">
            <div class="col-md-offset-9 col-md-10">
                @if (Model.Books.id == 0)
                {
                    <input type="submit" onclick="return confirm('Do you want to Save ..')" class="btn btn-primary col-md-3" value="Save" />
                }
                else
                {
                    <input type="submit" onclick="return confirm('Do you want to update ..')" class="btn btn-primary col-md-3" value="Update" />
                }
            </div>
        </div>
    </div>
    @Html.HiddenFor(m => m.Books.id)
}

CourseReg/Views/Subjects/Index.cshtml
@model List<CourseReg.ViewModel.Subject_VMQ>
@{
    ViewBag.Title = "Index";
}
<h2>Content List</h2>
<div class="col-md-offset-5 pull-right" style="margin-top:-40px">
    <a href="@Url.Action("Create","Subjects")" class="btn btn-primary">Create New</a>
</div>
<div class="row">

    <div class="col-md-12">
        <table class="table table-responsive table-bordered table-striped">
            <thead>
                <tr>
                    <th>Sr#</th>
                    <th>Semester Name</th>
                    <th>Book Name</th>
                   
                    <th>Action</th>
                </tr>
            </thead>
            @foreach (var lst in Model)
            {
                <tr>
                    <td>@lst.id</td>
                    <td>@lst.ChemsterName</td>
                    <td>@lst.Name</td>
                    <td>
                        <a href="@Url.Action("Edit", new { id = lst.id })" class="btn btn-primary" data-toggle="tooltip" data-placement="left" title="Click Me To Edit">Edit</a>
                        <a href="@Url.Action("Delete", new { id = lst.id })" class="btn btn-danger" data-toggle="tooltip" data-placement="left" title="Click Me To Delte">Delete</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>